global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts-nat-ha.yml

scrape_configs:
  # Node exporters on gateways
  - job_name: 'gateways-node'
    static_configs:
      - targets: ['gw1:9100', 'gw2:9100']

  # Not strictly required; node_exporter already exposes textfile metrics at /metrics
  - job_name: 'textfile-nat-ha'
    metrics_path: /metrics
    static_configs:
      - targets: ['gw1:9100','gw2:9100']
