---
# roles/nat_conntrack/handlers/main.yml
- name: Reload nftables
  listen: Reload nftables
  command: nft -f /etc/nftables.conf

- name: Restart conntrackd
  listen: Restart conntrackd
  systemd:
    name: conntrackd
    state: restarted
    enabled: yes
